### ISSUE TITLE
Dispensers don't refill recharges in new Anchors.

### ISSUE THREAD

**Issue by SpiderKolo** [cominixo/MoreRespawnAnchors#1]
Title says it all.

Vanilla Anchors can be charged with Glowstone manually or using Dispenser, while Modded variants have to be filled manually.
Because Dispensers can fill the Anchors, Netherite variant makes no sense because you can make a system where a redstone machine can detect and refill the Anchors when they lose some charges.

It would be nice if Netherite variant have a unique feature for players on respawn...
Maybe like give a Fire Reistance and Resistance for Nether Anchor and Slow Falling and Resistance for End Anchor?
Maybe when taking damage from Lava it teleports you to linked Netherite Respawn Nether Anchor?
Maybe you could do the same with Netherite Respawn End Anchor but for Void damage?

I mean... there got to be some more uses to make Netherite variant worth crafting.

**Comment by cominixo** [comment]
Totally missed the dispensers behavior, should be simple to fix.
For the Netherite changes, those are pretty good ideas, might implement those too. Thanks for the suggestions!

**Comment by cominixo** [comment]
The dispenser behavior was fixed in the latest commit https://github.com/cominixo/MoreRespawnAnchors/commit/fa4aadf3ed008c936b276c8b65fe9819069784f5 , will upload a release soon. Closing this for now, I'll consider the Netherite variant changes for a future update.
