### ISSUE TITLE
Netherite Variant of Anchor Blocks is not immune to Fire and Lava.

### ISSUE THREAD

**Issue by SpiderKolo** [cominixo/MoreRespawnAnchors#2]
Title says it all.

This one is just a simple bug I found.
Wanted to keep it separate from the other one as it is a different issue.

While their main functionality is to hold more charges, it would make a lot of sense if they would be also immune to Fire and Lava too since they are covered in Netherite.

**Comment by cominixo** [comment]
Oh yeah, missed that, should be an easy fix. Thanks for the report!

**Comment by cominixo** [comment]
Fixed in the latest commit https://github.com/cominixo/MoreRespawnAnchors/commit/fa4aadf3ed008c936b276c8b65fe9819069784f5 , will upload a release soon.
