### ISSUE TITLE
Client crash with Hydrogen during initialization 

### ISSUE THREAD

**Issue by SleepyTonia** [cominixo/MoreRespawnAnchors#4]
The title says it all. MoreRespawnAnchors runs perfectly without [Hydrogen](https://github.com/CaffeineMC/hydrogen-fabric), but put the two together and you get this:

> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'morerespawnanchors'!
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointClient.start(EntrypointClient.java:32)
> 	at net.minecraft.class_310.<init>(class_310.java:437)
> 	at net.minecraft.client.main.Main.main(Main.java:177)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:498)
> 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
> 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
> 	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)
> Caused by: java.lang.ExceptionInInitializerError
> 	at java.lang.Class.forName0(Native Method)
> 	at java.lang.Class.forName(Class.java:348)
> 	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:45)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112)
> 	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99)
> 	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184)
> 	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37)
> 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50)
> 	... 11 more
> Caused by: java.lang.IllegalArgumentException: Cannot get property class_2758{name=charges, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]} as it does not exist in Block{minecraft:air}
> 	at net.minecraft.class_2688.method_11654(class_2688.java:95)
> 	at me.cominixo.morerespawnanchors.MoreRespawnAnchors.lambda$static$0(MoreRespawnAnchors.java:28)
> 	at net.minecraft.class_4970$class_4971.<init>(class_4970.java:626)
> 	at net.minecraft.class_2680.<init>(class_2680.java:17)
> 	at net.minecraft.class_2689.method_28484(class_2689.java:61)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
> 	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
> 	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
> 	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
> 	at net.minecraft.class_2689.<init>(class_2689.java:59)
> 	at net.minecraft.class_2689$class_2690.method_11668(class_2689.java:154)
> 	at net.minecraft.class_2248.<init>(class_2248.java:178)
> 	at me.cominixo.morerespawnanchors.block.BaseRespawnAnchor.<init>(BaseRespawnAnchor.java:36)
> 	at me.cominixo.morerespawnanchors.block.NetheriteRepawnAnchor.<init>(NetheriteRepawnAnchor.java:11)
> 	at me.cominixo.morerespawnanchors.MoreRespawnAnchors.<clinit>(MoreRespawnAnchors.java:28)
> 	... 19 more

`morerespawnanchors-1.0.1.jar`
`hydrogen-fabric-mc1.16.5-0.2.jar`
`fabric-api-0.34.2+1.16.jar`
`fabric-loader-0.11.3-1.16.5`
`Minecraft 1.16.5`

**Comment by gliscowo** [comment]
I just now noticed this issue is exactly what my PR fixes. Should you still need it, my fork fixes this issue and should my PR not get merged I can get you a build

**Comment by cominixo** [comment]
Just released 1.0.2 with the fix from #7, let me know if there are any issues
